name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.10.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  go_router: ^14.6.3
  googleapis: ^13.2.0
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
