// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpmlZXznFvbehsbn5XrpoE0q66qlvEc5A',
    appId: '1:247083996911:web:c4eefb9525b6dc7f8b2d1a',
    messagingSenderId: '247083996911',
    projectId: 'innate-star-447108-g0',
    authDomain: 'innate-star-447108-g0.firebaseapp.com',
    storageBucket: 'innate-star-447108-g0.firebasestorage.app',
    measurementId: 'G-J0V1RVKC27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqOaVDiofq4tPytMt4GFB63zfTTJF008',
    appId: '1:247083996911:android:a15b1993a23d237f8b2d1a',
    messagingSenderId: '247083996911',
    projectId: 'innate-star-447108-g0',
    storageBucket: 'innate-star-447108-g0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYdUJ_j3b-qiNM8GnNkwLxtpQp5HLJhtk',
    appId: '1:247083996911:ios:86b7bf0c5bd10d558b2d1a',
    messagingSenderId: '247083996911',
    projectId: 'innate-star-447108-g0',
    storageBucket: 'innate-star-447108-g0.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYdUJ_j3b-qiNM8GnNkwLxtpQp5HLJhtk',
    appId: '1:247083996911:ios:86b7bf0c5bd10d558b2d1a',
    messagingSenderId: '247083996911',
    projectId: 'innate-star-447108-g0',
    storageBucket: 'innate-star-447108-g0.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpmlZXznFvbehsbn5XrpoE0q66qlvEc5A',
    appId: '1:247083996911:web:df2f19cdef4385678b2d1a',
    messagingSenderId: '247083996911',
    projectId: 'innate-star-447108-g0',
    authDomain: 'innate-star-447108-g0.firebaseapp.com',
    storageBucket: 'innate-star-447108-g0.firebasestorage.app',
    measurementId: 'G-L6WWFF5SCK',
  );
}
